app:
    resource: "@AppBundle/Controller/"
    type:     annotation

home:
    path: '/'
    defaults: { _controller: AppBundle:Site:index }

sale:
   path: '/sales'
   defaults: { _controller: AppBundle:Site:sale }

rent:
   path: '/rent'
   defaults: { _controller: AppBundle:Site:rent }

contact:
   path: '/contact'
   defaults: { _controller: AppBundle:Site:contact }

single_service:
   path: '/{service_name}'
   defaults: { _controller: AppBundle:ServicesPage:singleService }

not_found:
   path: '/page-not-found'
   defaults: { _controller: AppBundle:Site:notFound }