app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

admin:
    path: '/admin'
    defaults: { _controller: AppBundle:Admin\Admin:dashboard }

#home:
#    path: '/'
#    defaults: { _controller: AppBundle:Site:index }

fos_user_security_login:
    path: '/login'
    defaults: { _controller: AppBundle:Security:login }

logout:
    path: '/logout'
    defaults: { _controller: FOSUserBundle:Security:logout }

#contact:
#   path: '/contact'
#   defaults: { _controller: AppBundle:Site:contact }

#not_found:
#   path: '/404'
#   defaults: { _controller: AppBundle:Site:notFound }
#
#sale:
#   path: '/sales'
#   defaults: { _controller: AppBundle:Site:sale }
#
#sale.sort_by_type:
#    path: '/sales/{type}'
#    defaults: { _controller: AppBundle:Site:salesByType}
#
#sale.single_object:
#    path: '/sales/{type}/{object}'
#    defaults: { _controller: AppBundle:Site:singleObjectView }

#rent:
#   path: '/rent'
#   defaults: { _controller: AppBundle:Site:rent }
#
#rent.sort_by_type:
#   path: '/rent/{type}'
#   defaults: { _controller: AppBundle:Site:rentByType }
#
#rent.single_object:
#    path: '/rent/{type}/{object}'
#    defaults: { _controller: AppBundle:Site:singleObjectView }

admin.contact:
    path: '/admin/contact'
    defaults: { _controller: AppBundle:Admin\Contact:manage }

admin.object:
    path: '/admin/object'
    defaults: { _controller: AppBundle:Admin/Object:listObject}

admin.object.add:
    path: '/admin/object/add'
    defaults: { _controller: AppBundle:Admin/Object:addObject}

admin.object.edit:
    path: '/admin/object/{object}/edit'
    defaults:  { _controller: AppBundle:Admin/Object:editObject }

admin.object.delete:
    path: '/admin/object/delete/{object}'
    defaults: { _controller: AppBundle:Admin/Object:deleteObject }

admin.object.bin:
    path: '/admin/object/bin'
    defaults: { _controller: AppBundle:Admin/Object:objectBin }

admin.object.bin.repair:
    path: '/admin/object/{object}/repair'
    defaults: { _controller: AppBundle:Admin/Object:repairObject }

admin.object.bin.remove:
    path: '/admin/object/{object}/remove'
    defaults: { _controller: AppBundle:Admin/Object:removeFromBin }