app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

admin:
    path: '/admin'
    defaults: { _controller: AppBundle:Admin\Admin:dashboard }

fos_user_security_login:
    path: '/login'
    defaults: { _controller: AppBundle:Security:login }

logout:
    path: '/logout'
    defaults: { _controller: FOSUserBundle:Security:logout }

#not_found:
#   path: '/404'
#   defaults: { _controller: AppBundle:Site:notFound }
#
