app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

home:
    path: '/'
    defaults: { _controller: AppBundle:Site:index }

admin:
    path: '/admin'
    defaults: { _controller: AppBundle:Admin\Admin:dashboard }

fos_user_security_login:
    path: '/login'
    defaults: { _controller: AppBundle:Security:login }

logout:
    path: '/logout'
    defaults: { _controller: FOSUserBundle:Security:logout }

sale:
   path: '/sales'
   defaults: { _controller: AppBundle:Site:sale }

rent:
   path: '/rent'
   defaults: { _controller: AppBundle:Site:rent }

contact:
   path: '/contact'
   defaults: { _controller: AppBundle:Site:contact }

not_found:
   path: '/not-found'
   defaults: { _controller: AppBundle:Site:notFound }

service_page.list:
   path: '/admin/page/list'
   defaults: { _controller: AppBundle:Admin\Page:listPages }

service_page.manage:
   path: '/admin/page/{page}'
   defaults: { _controller: AppBundle:Admin\Page:managePage, page: null }