app:
    resource: "@AppBundle/Controller/"
    type:     annotation

home:
    path: '/'
    defaults: { _controller: AppBundle:Site:index }

sale:
   path: '/sales'
   defaults: { _controller: AppBundle:Site:sale }