parameters:
#    parameter_name: value

services:
    gedmo.listener.timestampable:
        class: Gedmo\Timestampable\TimestampableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, ['@annotation_reader'] ]

    app.file_uploader:
        class: AppBundle\Service\FileUploader
        arguments: ["@doctrine.orm.entity_manager", "%upload_directory%"]

    app.image_relations:
        class: AppBundle\Listener\FileRelationSubscriber
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    app.symfony_finder:
        class: Symfony\Component\Finder\Finder
        public: false

    app.crudable:
        class: AppBundle\Service\Crudable
        arguments: ["@doctrine.orm.entity_manager", "@app.file_uploader", "@security.token_storage", "@service_container", "@app.symfony_finder"]