# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.image_uploader:
        class: AppBundle\Service\ImageUploader
        arguments: ["@doctrine.orm.entity_manager", "%upload_directory%"]
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
