# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.image_uploader:
        class: AppBundle\Service\ImageUploader
        arguments: ["@doctrine.orm.entity_manager", "%upload_directory%"]

    app.image_relations:
        class: AppBundle\Listener\ImageRelationSubscriber
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    app.crudable:
        class: AppBundle\Service\Crudable
        arguments: ["@doctrine.orm.entity_manager", "@app.image_uploader", "@security.token_storage"]